apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signature
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  admission: true #default field to avoid out of sync message
  background: false #default field to avoid out of sync message
  emitWarning: false #default field to avoid out of sync message
  validationFailureAction: Enforce
  background: false
  rules:
    - name: verify-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "595981035245.dkr.ecr.ap-south-1.amazonaws.com/atul-devops-lab/poc-application:*"
          required: true #default field to avoid out of sync message
          mutateDigest: true #default field to avoid out of sync message
          verifyDigest: true #default field to avoid out of sync message
          useCache: true #default field to avoid out of sync message
          attestors:
            - entries:
                - keyless:
                    subject: "https://github.com/atul-devops-lab/POC-application/.github/workflows/ci.yml@refs/heads/main"
                    issuer: "https://token.actions.githubusercontent.com"
                    rekor:
                      url: https://rekor.sigstore.dev
                      signatureAlgorithm: sha256 #default field to avoid out of sync message
